---
- hosts: group-public-network-grafana
  remote_user: evg
  become: yes
  become_user: root
  tasks:
    - name: Download grafana
      become: true
      get_url:
       url: https://dl.grafana.com/oss/release/grafana_9.2.4_amd64.deb
       dest: /home/evg/grafana_9.2.4_amd64

    - name: Install grafana
      become: true
      yum:
        name: /home/evg/grafana_9.2.4_amd64
        state: present

    - name: "grafana start"
      systemd:
        name: grafana server
        state: started
        enabled: yes
...
